# .github/workflows/deploy-staging.yml
name: Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    environment: staging
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and run Docker container
        run: |
          docker pull ghcr.io/kosasih/pi-supernode:${{ github.sha }}
          docker stop pi-supernode || true
          docker rm pi-supernode || true
          docker run -d \
            --name pi-supernode \
            -p 8000:8000 \
            -e REDIS_URL=${{ secrets.REDIS_URL }} \
            -e STELLAR_HORIZON_URL=${{ secrets.STELLAR_HORIZON_URL_TESTNET }} \
            -e ISSUER_SECRET=${{ secrets.ISSUER_SECRET }} \
            -e SOURCE_SECRET=${{ secrets.SOURCE_SECRET }} \
            -e CHAINLINK_FEED_ADDRESS=${{ secrets.CHAINLINK_FEED_ADDRESS }} \
            -e BAND_FEED_ADDRESS=${{ secrets.BAND_FEED_ADDRESS }} \
            -e MOCK_FEED_ADDRESS=${{ secrets.MOCK_FEED_ADDRESS }} \
            -e PRICE_TARGET=314159.0 \
            -e MAX_SUPPLY_DEVIATION=0.01 \
            -e MIN_ADJUSTMENT_THRESHOLD=1000 \
            -e PRICE_CACHE_TTL=60 \
            ghcr.io/kosasih/pi-supernode:${{ github.sha }}

      - name: Verify deployment
        run: |
          sleep 10
          curl -f http://localhost:8000/health || exit 1
